name: Logistics ETL Pipeline

# Define quando a automação será executada
on:
  schedule:
    - cron: '0 0 * * 1' # Executa toda segunda-feira à meia-noite (UTC)
  workflow_dispatch:   # Permite que você execute manualmente pelo botão no GitHub

jobs:
  build_and_run:
    runs-on: ubuntu-latest # Usa um servidor Linux gratuito do GitHub

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas kaggle pyarrow fastparquet

      - name: Executar Script de ETL
        # Aqui conectamos os Secrets do GitHub às variáveis que o script lê
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: python scripts/main_etl.py

      - name: Salvar resultados no Repositório
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add output/base_logistica_olist.parquet
          git commit -m "Auto-update: Base de dados atualizada via Pipeline" || exit 0
          git push

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt